### ISSUE TITLE
AutoComplete

### ISSUE THREAD

**Issue by ghost** [mozfet/meteor-autoform-materialize#20]
Hi there,

autoform materialize is a great work, and i use it a lot, but i need some feature on some component, i need to use autocomplete in multiple select which is very useful if there is so many options, for your reference 
https://github.com/icefox0801/materialize-autocomplete

thanks

**Comment by mozfet** [comment]
Single autocomplete is done. Multiple coming soon. There is an issue with the values being returned being that of the label; I'll try to fix that together with multiple in the coming days.

**Comment by ghost** [comment]
Great,  waiting for the multiple autocomplete...

**Comment by mozfet** [comment]
I'm making progress with autocompete multiple. Very difficult if I must say so. In any case I nearly got it working like a select, in fact it uses a hidden select to carry the autoform value and validation. My main concern is that I cannot see a way to make it possible to add items that are not on the list. Do you need that, or is your list of autocomplete items complete and mutually exclusive like a select?

**Comment by mozfet** [comment]
```
autoCompleteMultiple: {
    type: Array,
    label: 'Auto Complete Multiple',
    autoform: {
      type: 'autocomplete',
      options: () => {
        return [
          {
            label: 'Alpha',
            value: 'ALPHA'
          },
          {
            label: 'Animal',
            value: 'ANIMAL'
          },
          {
            label: 'Always',
            value: 'ALWAYS'
          },
          {
            label: 'Anytime',
            value: 'ANYTIME'
          },
          {
            label: 'Bravo',
            value: 'BRAVO'
          },
          {
            label: 'Bedtime',
            value: 'BEDTIME'
          }
        ];
      },
      autoComplete: {
        displayLimit: 3,
        multiple: true,
        minSize: 1, // for some unknown reason simple schema min is not propaged to auto complete input, thus we define it here
        maxSize: 3  // for some unknown reason simple schema max is not propaged to auto complete input, thus we define it here
      }
    }
  },
  'autoCompleteMultiple.$': {
      type: String,
      allowedValues: ['ALPHA', 'ANIMAL', 'ALWAYS', 'ANYTIME']
  }
```

**Comment by ghost** [comment]
What do you mean by add an item which is not in the list?  Right now,  im using select multiple which is good,  but i need to scroll down to select the list,  if have list about 300 hundreds,  it will take some times,  what i need is select multiple with autocomplete...  Do i need to reinstall the package to try the autocomplete??

**Comment by ghost** [comment]
cannot get the autocomplete working... after install the materialize-autocomplete, add it to schema... its only show the label... for both multiple and single

**Comment by mozfet** [comment]
I have not uploaded multiple yet... only single works in the Atmosphere package... and then not very well. I had to rework the entire jquery plugin because it interfered with auto form, and the multiple function was not implemented correctly (there was no way to retrieve the value of a multiple autocomplete. I had to build that with a hidden select. There are still a few bugs left...  I did not mean for you to try, I meant to show you where I'm going ;)

To autocomplete it needs a list of items to autocomplete from. But lets say you want to ask the user to enter a car manufacturer, you add all the popular ones to the list, but the user has an lesser known manufacturer. You still want the user to enter the car manufacturer, because that is the value of the data you want. With a select you cannot select an option that is not on the list, but in an autocomplete you can type it. I'm about to get autocomplete to work the same as a single/multiple select, but I do not yet have a solution how to add options not in the hidden select.

EDIT: Re-reading your answer, you are looking for the same functionality as a multiple select in autocomplete. That is nearly ready. I'll upload it today.

**Comment by mozfet** [comment]
So in the example above... do you want the user to also be able to add the value CHARLIE?

**Comment by mozfet** [comment]
Singular and Multiple Auto Complete is working, but see open issues #21 and #22. I've uploaded v3.3.0 to Atmosphere. See the readme for usage, and the playground for extended examples.
