### ISSUE TITLE
Unable to build, missing scss file

### ISSUE THREAD

**Issue by RedRelay** [mozfet/meteor-autoform-materialize#25]
With a fresh Meteor 1.6.0.1 project install a bit edited to support npm@5, I can't run my app with autoform-materialize.

The modification I've done is just create a root `packages` to put materialize (0.100.2) into and change its dependencies to use node-sass 4.7.2 instead of 4.5.4. This update was mandatory to avoid a 404 not found during building.

With the following packages file : 
``` 
aldeed:autoform
fourseven:scss
materialize:materialize
mozfet:autoform-materialize
```

I've got the following error : 
```
   While processing files with fourseven:scss (for target web.browser):
   /packages/mozfet_autoform-materialize/style.scss: Scss compiler error: File to import: {}/node_modules/materialize-css/sass/materialize.scss not found in file:
   C:/Users/aduponchel/Documents/RD/meteor/sample-subscribing/{mozfet:autoform-materialize}/style.scss
```

**Comment by mozfet** [comment]
Hmmm... I have not tested with the Atmosphere Materialize package in a while and the new features recently added to mozfet:autoform-materialize use SASS for styling... there is no way to transport SASS uncompiled in an Atmosphere package so that it can be included from an SCSS file in an app or another package in order to, for example change the color scheme. 

Thus in order to support SASS, the mozfet:autoform-materialize dependency is on the NPM Materialise package for the uncompiled Materialize SCSS sources... Unfortunately, this now means that I have unwittingly killed support for the Atmosphere Materialize.

Truth is that I was considering to drop support for the Atmosphere package in any case. This is because using Atmosphere wrapper packages of NPM packages is considered bad practice and should be flagged as unnecessary wrappers on Atmosphere... Looks like I have unconsciously made my decision...

Another reason to not use Atmosphere Materialize package is that it does not support customizing the colors of the resulting app and thus is not useful unless dirty pink is your color, and you cannot use materialize color templates either...

I thus recommend you to start using the NPM Materialize Package directly, instead of the Atmosphere wrapper, and then this error should also go away. I will update the readme to announce the removal of support for the Atmosphere package.

If you must use the Atmosphere Materialize package, then you may have to roll back a few versions of this package...

**Comment by RedRelay** [comment]
Thank you for your complete answer. I just began using Meteor few month ago and I am looking for good practice as much as possible. I will use NPM packages directly. I think it is better anyway, as I mention, the Materialize Atmosphere package seems broken too, and atm require manual action to compile correctly on Meteor 1.6.

**Comment by mozfet** [comment]
Check out the readme for this repository. It includes detailed instructions for installing and using the NPM Package of Materialize with Meteor.
