### ISSUE TITLE
color.scss not found

### ISSUE THREAD

**Issue by KoenLav** [mozfet/meteor-autoform-materialize#43]
After updating to Meteor 1.7 (also in RC stage) I received this error, on Windows 10 x64:

/packages/mozfet_autoform-materialize/style.scss:
Scss compiler error:
File to import: {}/node_modules/materialize-css/sass/components/color.scss not found in file:

**Comment by mozfet** [comment]
I've not yet tested the package with Meteor 1.7. Can you confirm that that Materialize CSS NPM package is installed in the app project and the path exists?

**Comment by KoenLav** [comment]
This is definitely the case.

**Comment by mozfet** [comment]
Ok, I read the [Meteor Release 1.7 thread](https://github.com/meteor/meteor/pull/9826)... not sure how I can make it work in the package if the framework drops support for SCSS imports from node packages, I cannot believe that is intentional and agree with your statement that packages need this functionality... 

I'm not sure what/why mlink is/needed, but creating symlinks in the imports folder to importing node packages work seem counterintuitive the meteor no-config approach.

That being said, it is working on 1.6.1.1 (on OSX) which is the latest stable release - if it breaks on the official released 1.7 it will be a setback and the only workaround I can think of is that scss will have to be manually installed in the app or some kind of symlink setup instructions needed to get the package to work...  :( 

I guess I will wait and see what happens when 1.7 is officially released. Unless someone else has any ideas.

**Comment by KoenLav** [comment]
Meteor has resolved this issue, closing this.
