### ISSUE TITLE
node_modules/materialize-css/sass/components/color.scss not found

### ISSUE THREAD

**Issue by suryaiiit** [mozfet/meteor-autoform-materialize#60]
While processing files with fourseven:scss (for target web.browser):
   /packages/mozfet_autoform-materialize/style.scss: Scss compiler error: File to import:
   {}/node_modules/materialize-css/sass/components/color.scss not found in file:
   /Users/surya/Documents/Projects/adms/{mozfet:autoform-materialize}/style.scss
   
   
   While processing files with fourseven:scss (for target web.browser.legacy):
   /packages/mozfet_autoform-materialize/style.scss: Scss compiler error: File to import:
   {}/node_modules/materialize-css/sass/components/color.scss not found in file:
   /Users/surya/Documents/Projects/adms/{mozfet:autoform-materialize}/style.scss
   
I'm not sure from is this file being referenced.
This file clearly states different color.scss files
https://github.com/mozfet/meteor-autoform-materialize/blob/master/style.scss

It looks like the meteor package is not updated .... (still has @import "{}/node_modules/materialize-css/sass/components/color.scss";)

Also, please update the readme file. Thanks.

**Comment by suryaiiit** [comment]
For now, I've created a file @ {}/node_modules/materialize-css/sass/components/color.scss 
with this content:
@import "_color-variables.scss";
@import "_color-classes.scss";

and it works fine.

I think the package is not in sync.

**Comment by mozfet** [comment]
Hmmm, latest version of this package is 4.0.11, which is the same as on Atmosphere, and I'm using mozfet:autoform-materialize@4.0.11 from Atmosphere in a production environment. So I'm not sure what's going wrong here. I will try a clean version of the playground and try to see if I can reproduce it there...

I got tired of manually adding my color schema to Materialize manually every time the node package updates, so I am now using my own color-variables.scss, variables.scss and materialize.scss, (with hard forked content from the node package scss) instead of those in the NPM package. 

That being said, the readme file has become more of a how-to install MaterializeCSS on Meteor, than how to use this package, and adding my 'project side customisations' will inflate it even more - so I will split the MaterializeCSS installation info into its own GIST and link the readme to that.

**Comment by mozfet** [comment]
I've tested 4.0.11 in a clean install of the sandbox. It works perfectly with:
```
@import "../node_modules/materialize-css/sass/materialize.scss"
@import "{mozfet:autoform-materialize}/style.scss"
```

Please confirm the version of the package in your ```.meteor/versions file``` it should be mozfet:autoform-materialize@4.0.11

**Comment by mozfet** [comment]
Unable to reproduce. Closed due to inactivity.
